// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userService.proto

package ru.rb.onion.grpc.controller.proto;

public interface GetUserRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.rb.onion.grpc.controller.proto.GetUserRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
