// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userService.proto

package ru.rb.onion.grpc.controller.proto;

public interface SaveUserResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.rb.onion.grpc.controller.proto.SaveUserResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   */
  long getId();
}
