// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userService.proto

package ru.rb.onion.grpc.controller.proto;

public final class UserService {
  private UserService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_rb_onion_grpc_controller_proto_SaveUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_rb_onion_grpc_controller_proto_SaveUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_rb_onion_grpc_controller_proto_SaveUserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_rb_onion_grpc_controller_proto_SaveUserResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_rb_onion_grpc_controller_proto_GetUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_rb_onion_grpc_controller_proto_GetUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_rb_onion_grpc_controller_proto_GetUserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_rb_onion_grpc_controller_proto_GetUserResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021userService.proto\022!ru.rb.onion.grpc.co" +
      "ntroller.proto\",\n\017SaveUserRequest\022\014\n\004nam" +
      "e\030\001 \001(\t\022\013\n\003age\030\002 \001(\005\"\036\n\020SaveUserResponse" +
      "\022\n\n\002id\030\001 \001(\003\"\036\n\016GetUserRequest\022\014\n\004name\030\001" +
      " \001(\t\">\n\017GetUserResponse\022\014\n\004name\030\001 \001(\t\022\013\n" +
      "\003age\030\002 \001(\005\022\020\n\010identity\030\003 \001(\0032\352\003\n\016UserSer" +
      "viceApi\022v\n\013saveRusUser\0222.ru.rb.onion.grp" +
      "c.controller.proto.SaveUserRequest\0323.ru." +
      "rb.onion.grpc.controller.proto.SaveUserR" +
      "esponse\022s\n\ngetRusUser\0221.ru.rb.onion.grpc" +
      ".controller.proto.GetUserRequest\0322.ru.rb" +
      ".onion.grpc.controller.proto.GetUserResp" +
      "onse\022v\n\013saveEngUser\0222.ru.rb.onion.grpc.c" +
      "ontroller.proto.SaveUserRequest\0323.ru.rb." +
      "onion.grpc.controller.proto.SaveUserResp" +
      "onse\022s\n\ngetEngUser\0221.ru.rb.onion.grpc.co" +
      "ntroller.proto.GetUserRequest\0322.ru.rb.on" +
      "ion.grpc.controller.proto.GetUserRespons" +
      "eB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ru_rb_onion_grpc_controller_proto_SaveUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ru_rb_onion_grpc_controller_proto_SaveUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_rb_onion_grpc_controller_proto_SaveUserRequest_descriptor,
        new String[] { "Name", "Age", });
    internal_static_ru_rb_onion_grpc_controller_proto_SaveUserResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ru_rb_onion_grpc_controller_proto_SaveUserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_rb_onion_grpc_controller_proto_SaveUserResponse_descriptor,
        new String[] { "Id", });
    internal_static_ru_rb_onion_grpc_controller_proto_GetUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ru_rb_onion_grpc_controller_proto_GetUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_rb_onion_grpc_controller_proto_GetUserRequest_descriptor,
        new String[] { "Name", });
    internal_static_ru_rb_onion_grpc_controller_proto_GetUserResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ru_rb_onion_grpc_controller_proto_GetUserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_rb_onion_grpc_controller_proto_GetUserResponse_descriptor,
        new String[] { "Name", "Age", "Identity", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
